apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pro-motors.fullname" . }}-storage
  labels:
    {{- include "pro-motors.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  storageClassName: {{ .Values.persistence.storageClass | default (include "pro-motors.storageClass" .) }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
