apiVersion: v2
name: pro-motors
description: A Laravel API application with API, Queue and Scheduler services
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - laravel
  - api
  - queue
  - scheduler
